version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: dotnet test C:\projects\problem-linkedlistcsharp-244et\TestLinkedListLibrary\TestLinkedListLibrary.csproj
